# Generated by Django 5.0.1 on 2024-01-26 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile1', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=15, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='crm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_options', models.CharField(choices=[('visited', 'Visited'), ('negotiation', 'Negotiation'), ('loss', 'Loss')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('person_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price_from', models.DecimalField(decimal_places=0, max_digits=12)),
                ('price_to', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('installment', models.BooleanField(default=False)),
                ('prop_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural')], max_length=20)),
                ('persontype', models.CharField(choices=[('seller', 'Seller'), ('purchaser', 'Purchaser')], max_length=20)),
                ('main_prop', models.CharField(choices=[('plot', 'Plot'), ('house', 'House')], max_length=20)),
                ('profile_names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.profile')),
            ],
        ),
    ]
