# Generated by Django 5.0.1 on 2024-01-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='size_unit',
            field=models.CharField(choices=[('sqf', 'Square Feet'), ('marla', 'Marla'), ('kanal', 'Kanal')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
